apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-dash-peterayoub-me""
  namespace: dashboard-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "ingress-sites"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dash-peterayoub-me"
    nginx.ingress.kubernetes.io/ssl-redirect: "false" #change it after ssl
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" #change it after ssl
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/set-real-ip-from: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/x-forwarded-for: "$proxy_add_x_forwarded_for"
    nginx.ingress.kubernetes.io/proxy-set-headers: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
spec:
  ingressClassName: "ingress-sites"
  rules:
  - host: dash.peterayoub.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dash-peterayoub-me
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dash-peterayoub-me
            port:
              number: 443
  - host: www.dash.peterayoub.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dash-peterayoub-me
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dash-peterayoub-me
            port:
              number: 443
  tls:
    - hosts:
      - dash.peterayoub.me
      - www.dash.peterayoub.me
      secretName: dash-peterayoub-me-tls
