apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dash-peterayoub-me
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@dash.peterayoub.me
    privateKeySecretRef:
      name: letsencrypt-prod-dash-peterayoub-me
    solvers:
    - http01:
        ingress:
          class: "ingress-sites"
