apiVersion: v1
kind: PersistentVolume
metadata:
  name: dash-peterayoub-me-pv
  namespace: dashboard-namespace-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-storage"
  nfs:
    path: /home/ubuntu/shared/
    server: 10.7.112.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dash-peterayoub-me-pvc
  namespace: dash-peterayoub-me
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-storage"
